# Generated by Django 4.0.1 on 2022-02-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
